{
 "title": "ぴよログ データ分析",
 "time": { "from": "now-90d", "to": "now" },
 "panels": [
  {
   "title": "昼寝回数と夜に起きる回数の日次推移",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "piyolog-analytics",
     "rawSql": "SELECT date, nap_count, night_wakeup_count FROM stats"
    }
   ]
  },
  {
   "title": "昼寝時間と夜寝時間の日次推移",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "dataset": "piyolog-analytics",
     "rawSql": "SELECT date, nap_minute, night_sleep_minute FROM stats"
    }
   ]
  },
  {
   "title": "昼寝時間と夜に起きている時間の日次推移",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "dataset": "piyolog-analytics",
     "rawSql": "SELECT date, nap_minute, night_wakeup_minute FROM stats"
    }
   ]
  },
  {
   "title": "ミルク回数の日次推移",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "piyolog-analytics",
     "rawSql": "SELECT date, milk_count FROM stats "
    }
   ]
  },
  {
   "title": "ミルク量の日次推移",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "mlitre" } },
   "targets": [
    {
     "dataset": "piyolog-analytics",
     "rawSql": "SELECT date, milk_count, milk_ml FROM stats"
    }
   ]
  }
 ]
}